openapi: 3.0.0
info:
  title: REST API
  description: REST APIs of Train Delay Predictor Application
  version: 1.0.0
servers:
  - url: http://127.0.0.1:4999/v1
    description: Server used for development

paths:
  /train-schedules:
    get:
      summary: Get train schedules
      description: Retrieves train schedules based on the provided source location
      parameters:
        - name: source
          in: query
          description: Source location for filtering train schedules
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/TrainSchedule'

definitions:
  TrainSchedule:
    type: object
    properties:
      train_id:
        type: string
      operational_train_number:
        type: string
      operator:
        type: string
      train_type:
        type: string
      from_location:
        type: string
      to_location:
        type: string
      advertised_time:
        type: string
        format: date-time