openapi: 3.0.0
info:
  title: REST API
  description: REST APIs of Train Delay Predictor Application
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/v1
    description: Server used for development
paths:
  /train-schedules:
    get:
      summary: Returns list of available train schedules.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainDetails'
  /predict-train-delay:
    post:
      summary: Predicts if train with the given details will be delayed or not
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainDetails'
      responses:
        '200':
          description: A JSON object with delay information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DelayInformation'
components:
  schemas:
    TrainDetails:
      type: object
      properties:
        train_id:
          type: string
          example: 346
        train_type:
          type: string
          example: PNA045
        operational_train_number:
          type: string
          example: 10346
        from_location:
          type: string
          example: De.ges
        to_location:
          type: string
          example: Cst
        operator:
          type: string
          example: SJ
        advertised_time:
          type: string
          example: 2024-03-19T04:35:00.000+01:00
        
      # Both properties are required
      required:  
        - train_id
        - train_type
        - operational_train_number
        - from_location
        - to_location
        - operator
        - advertised_time
    DelayInformation:
      type: object
      properties:
        delay:
          type: string
          example: Yes